resume_from_checkpoint: False
test_only: False

model_path: './results/best_model.pt'

num_epochs: 500
learning_rate: 0.001
weight_decay: 0.001
train_frac: 0.8
train_batch_size: 1
test_batch_size: 1

num_features: 142
hidden_size: 30
num_layers: 5
dropout: 0.1

data_path: './Data/'
plot_path: './results/'
label_scale: 90


