resume_from_checkpoint: False
test_only: False

model_path: './results/best_model.pt'

num_epochs: 500
learning_rate: 0.0001
weight_decay: 0.0001
train_frac: 0.8
train_batch_size: 5
test_batch_size: 1

num_features: 138
hidden_size: 500
num_layers: 5
dropout: 0.3

data_path: './Data/'
plot_path: './results/'
label_scale: 90
normalize: True


