resume_from_checkpoint: False
test_only: False

model_path: './results/best_model_1.pt'

num_epochs: 400
learning_rate: 0.0005
weight_decay: 0.000001
train_frac: 0.8
train_batch_size: 4
test_batch_size: 1

num_features: 142
hidden_size: 500
num_layers: 3
dropout: 0.15

data_path: './augmented_combined_dataset/'
plot_path: './results/'
label_scale: 400
normalize: False
sample: 'front'

manual_test_set: False


