resume_from_checkpoint: False
test_only: False

model_path: './results/best_model_1.pt'

num_epochs: 5
learning_rate: 0.0005
weight_decay: 0.00001
train_frac: 0.8
train_batch_size: 5
test_batch_size: 1

num_features: 142
hidden_size: 500
num_layers: 10
dropout: 0.35

data_path: './Data/'
plot_path: './results/'
label_scale: 90
normalize: True
sample: 'random'


