resume_from_checkpoint: False
test_only: False

model_path: './results/best_model_ruler_1.pt'

num_epochs: 500
learning_rate: 0.0001
weight_decay: 0.001
train_frac: 0.8
train_batch_size: 5
test_batch_size: 1

hidden_size: 400
num_layers: 6
dropout: 0.3

data_path: './Data/'
plot_path: './results/'
label_scale: 90
normalize: True


