program: lstm_papilarray.py
method: bayes
metric:
  name: abs_error/test
  goal: minimize
parameters:
  resume_from_checkpoint: 
    value: False
  test_only: 
    value: False
  model_path: 
    value: './results/best_model.pt'

  num_epochs: 
    value: 500
  learning_rate: 
    # values: [0.001]
    distribution: uniform
    min: 0.000001
    max: 0.01
  weight_decay: 
    # values: [0.0001]
    distribution: uniform
    min: 0
    max: 0.1
  train_frac: 
    value: 0.8
  train_batch_size: 
    # values: [1, 4, 64]
    distribution: int_uniform
    min: 1
    max: 32

  num_features: 
    value: 142
  hidden_size: 
    # values: [128, 256]
    distribution: int_uniform
    min: 8
    max: 2000
  num_layers: 
    # values: [3, 5]
    distribution: int_uniform
    min: 1
    max: 20
  dropout: 
    # values: [0.2, 0.1]
    distribution: uniform
    min: 0
    max: 0.75

  data_path: 
    value: './Data/'
  plot_path: 
    value: './results/'
  label_scale: 
    value: 90
  normalize: 
    values: [False, True]

  sample:
    values: ['random', 'center', 'front']

entity: deep-tactile-rotatation-estimation
project: LSTM_papilarray_sweep



