resume_from_checkpoint: False
test_only: False
model_path: './results/best_model_2.pt'

num_epochs: 200
learning_rate: 0.0001
weight_decay: 0
train_frac: 0.8
train_batch_size: 5
test_batch_size: 1

num_features: 142
hidden_size: 300
num_layers: 2
dropout: 0.2

data_path: './rotation-detection-IROS-2021/RobotData/'
plot_path: './results/'
label_scale: 90
normalize: False
sample: 'random'

